runtime: java11
instance_class: b4_1G

env_variables:
  envTarget: "gcp"
  SPRING_PROFILES_ACTIVE: "cloud-gcp"

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
  - url: /.*
    script: this field is required, but ignored


# resources:
#    cpu: 2
#    memory_gb: 4
#    disk_size_gb: 10  